### ISSUE TITLE
devel/hs-executable-path System.posix 

### ISSUE THREAD

**Issue by sajozsattila** [freebsd-haskell/ports#11]
Hello,

I tried to build some Haskell port on Dragonfly BSD where I find a problem in the devel/hs-executable-path port.  Because the DragonFly not in the supported OS list, I had to make a patch (files/patch-System-Environment-Executable.hs) which point to the FreeBSD.hs:

--- System/Environment/Executable.hs.orig	2011-12-01 21:09:29.000000000 +0000
+++ System/Environment/Executable.hs	2015-03-02 15:17:03.921735000 +0000
@@ -83,6 +83,11 @@
 import System.Environment.Executable.FreeBSD
 #endif
 
+#ifdef dragonfly_HOST_OS
+#define SUPPORTED_OS
+import System.Environment.Executable.FreeBSD
+#endif
+
 #ifdef netbsd_HOST_OS
 #define SUPPORTED_OS
 import System.Environment.Executable.BSD

When I try to make the patched port I get the following Error:

Preprocessing library executable-path-0.0.3...

System/Environment/Executable/FreeBSD.hs:25:8:
    Could not find module ‘System.Posix’
    It is a member of the hidden package ‘unix-2.7.0.1’.
    Perhaps you need to add ‘unix’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
*** Error code 1

It sounds like FreeBSD spec error, but I do not want to install a FreeBSD just for this, so could you test please.  I also would like to commit my patch in the freebsd-haskell if it is possible. 

Kind regards,
Attila Sajo

########################### Hungarian / Magyar ##########################
Szia,

Megprobaltam nehany port-ot DragonFly BSD-in leforditani es szerintem talaltam egy FreeBSD specifikus problemat.  Nem nagyon akartam csak ezert telepiteni egy FreeBSD-t szoval meg tesztelni kellene.  Mivel a DragonFly nincs a hardcoded OS listaban, ezert kellet egy foltot (files/patch-System-Environment-Executable.hs) csinalnom ami a FreeBSD.hs-re mutat: 

--- System/Environment/Executable.hs.orig	2011-12-01 21:09:29.000000000 +0000
+++ System/Environment/Executable.hs	2015-03-02 15:17:03.921735000 +0000
@@ -83,6 +83,11 @@
 import System.Environment.Executable.FreeBSD
 #endif
 
+#ifdef dragonfly_HOST_OS
+#define SUPPORTED_OS
+import System.Environment.Executable.FreeBSD
+#endif
+
 #ifdef netbsd_HOST_OS
 #define SUPPORTED_OS
 import System.Environment.Executable.BSD

Na most, a 'make' a kovetkezo hibauzenetett adja nekem erre:

Preprocessing library executable-path-0.0.3...

System/Environment/Executable/FreeBSD.hs:25:8:
    Could not find module ‘System.Posix’
    It is a member of the hidden package ‘unix-2.7.0.1’.
    Perhaps you need to add ‘unix’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
*** Error code 1

Ez nekem FreeBSD specifukus hibanak tunik.
Ha lehetseges akkor szeretnem a patch fajlt beolvasztani a projectekbe.

Udvozlet,
Sajo Attila

**Comment by pgj** [comment]
Aw, sorry I have just found this ticket.  I will look into this.

**Comment by pgj** [comment]
Perhaps the following patch solves your problem.  I have (build-)tested this on FreeBSD, and it appears to be working:

~~~~
diff --git a/devel/hs-executable-path/files/patch-System_Environment_Executable.hs b/devel/hs-executable-path/files/patch-System_Environment_Executable.hs
new file mode 100644
index 0000000..56ac0d8
--- /dev/null
+++ b/devel/hs-executable-path/files/patch-System_Environment_Executable.hs
@@ -0,0 +1,11 @@
+--- System/Environment/Executable.hs.orig      2011-12-01 21:09:29 UTC
++++ System/Environment/Executable.hs
+@@ -78,7 +78,7 @@ import System.Environment.Executable.Mac
+ import System.Environment.Executable.Linux
+ #endif
+ 
+-#ifdef freebsd_HOST_OS
++#if defined(freebsd_HOST_OS) || defined(dragonfly_HOST_OS)
+ #define SUPPORTED_OS
+ import System.Environment.Executable.FreeBSD
+ #endif
diff --git a/devel/hs-executable-path/files/patch-executable-path.cabal b/devel/hs-executable-path/files/patch-executable-path.cabal
new file mode 100644
index 0000000..350b9c3
--- /dev/null
+++ b/devel/hs-executable-path/files/patch-executable-path.cabal
@@ -0,0 +1,11 @@
+--- executable-path.cabal.orig 2011-12-01 21:09:30 UTC
++++ executable-path.cabal
+@@ -44,7 +44,7 @@ Library
+     Build-Depends:       unix
+     Other-Modules:       System.Environment.Executable.Linux
+     
+-  if os(freebsd) 
++  if os(freebsd) || os(dragonfly)
+     Build-Depends:       unix, directory
+     Other-Modules:       System.Environment.Executable.FreeBSD
+ 
~~~~

I can add commit this to the repository, if that works fine for you.  I think the problem was the you forgot to consider adding the `os(dragonfly)` condition for the package description (`.cabal`) file so the `unix` package could be properly configured before building.
